spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/account_service_database
    username: postgres
    password: postgres
  liquibase:
    enabled: true
server:
  port: 8081
springdoc:
  swagger-ui:
    config-url: http://localhost:8000/api
