spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/account_service_database
    username: postgres
    password: postgres
  liquibase:
    enabled: true
